---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - COVERAGE=true node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token:
            secure: "UFdwRzKx+hJS+qHThLwrRHIXndLe4CZcuGU3hv2bDPAiyzNqzFs/fkxHyl+Dgl0ZPOVkFQAaIXL7FDsVdVHMHYsiDZ4wf2OQE+4ZrAyoLOBTju6183axWej0c5QNBYLNV/WbPfr+L+rc7c1rykF9dE5tfx8FAqgrX6gnKkQbjVcHHh+TlyvdMxXZ/sg1tOEdZv4G3nwKBY10fpvDaQAQL4oBqCgNu0Vw/Z9unOyxpHaKIrGmHotIs/71mgGteNeCFHMJtg+4Eshj7D6jYC5zDhIAQLOcBAnvGjGMT5KqG/MthMlPj509Zu+rJoQtA1gVb4v8SVUtA8sMHhZdcXViAWbQhj8JVkiEGhZhF6LSnNvmkLBhb7al9aOVkGasoc10HKXyZkl8hBS310wwbsegn9fJx9ijpj5V8rIPyJM3XifYBVu3I8KCOEXYc/FY7K9COaVBpwGs2gF+6VyQCdcaR1JN2Bzv2lQFFRlwrDiu3xvxR7hx1OkPZ6gHELC/0yUTX5ls3u5Z0vrk/lAPezWMZ95EWnJHy/ouKW26CeHQ5z7x3lEAAK2hNaeIEkiAD1r5gRd65pOKUsr0mCaBi+qOca5em8AERyT/fcXyUZ9OwFwKXC1pIsMcnkj6JcSiUyxsc+pN/0Xv92LrfregQ32yo0eXo1nIiwnU8ifezZnRI3A="
